export { default as Breakfast1} from '../../../assets/imags/Breakfast1.jpg'
export { default as Breakfast2} from '../../../assets/imags/Breakfast2.jpg'
export { default as Breakfast3} from '../../../assets/imags/Breakfast3.jpg'
export { default as Breakfast4} from '../../../assets/imags/Breakfast4.jpg'
export { default as tagine} from '../../../assets/imags/tagine.jpg'